### PR TITLE
gadgetkeyboard.py: Fix keyboard emulator freezing on writing to file

### PR DESCRIPTION
**Pull request by skuusela**
On some rare occasions keyboard emulator freezes when it tries to write
to the file which acts as the emulator. It also freezes the whole AFT/DAFT
run. So do the writing on a separate process so it can be terminated if
it hangs.

Signed-off-by: Simo Kuusela <simo.kuusela@intel.com>

### CODE REVIEW

**Comment by igor-stoppa** [comment]
This looks more like a workaround than a fix: you retry if it fails, but the real fix would be to avoid the failure entirely.

**Comment by skuusela** [comment]
@igor-stoppa True it's more of a workaround. Sometimes it just freezes. I can do the same thing manually in terminal and writing to the '/dev/hidg0' just hangs and never finishes. Only thing that works seems to be to restart DUT/BBB or reconnect the USB cable. With this commit DUT will be restarted and usually the keyboard emulation works after that. But I'll try to see if there's a better solution.

**Comment by skuusela** [comment]
@igor-stoppa I found out that one problem might be that the testing harness initialization script is ran using /etc/rc.local. Because of that, the keyboard emulation seems to only work while DUT is booting or in BIOS. For example when DUT has booted Ubuntu, the keyboard emulation doesn't seem to work and it produces some error messages in dmesg. At least this is when writing to the keyboard emulation file hangs 100% of the time. If the script is ran manually after BBB has fully booted the keyboard emulation works fine and doesn't produce these error messages. I also tried cron with '@reboot' to run the script, but this doesn't work if BBB is cold booted. One option would be to run the script when DAFT/AFT is ran first time after reboot. Thoughts?

**Comment by igor-stoppa** [comment]
I would say use systemd, it should provide support for whatever scenario you want to cover.

**Comment by skuusela** [comment]
@igor-stoppa #83 At least fixes the issue that the keyboard emulation is not working in other than BIOS. It might also fix the issue with it randomly hanging even in BIOS but can't be sure because the issue is so rare. So for that reason I would still merge also this.

**Pull request merged**
