### PR TITLE
testing_harness: Remove the need for "test_mode" parameter

### PR DESCRIPTION
**Pull request by skuusela**
Change the logic how we check if we have correctly booted support image
or target image. Instead of checking service_mode parameter when booting
support image and test_mode parameter when booting target image, only
use the service_mode parameter to see if we have booted support image
or target image.

New boot functions has been added to pcdevice.py and also these functions
have been added as abstract functions to device.py to indicate that these
functions are expected to be in every new device class. With these new
functions boot_device_to_mode function can be removed as every device
should have functions to boot specific modes.

Signed-off-by: Simo Kuusela <simo.kuusela@intel.com>

### CODE REVIEW

**Comment by skuusela** [comment]
There was some connection error in Jenkins, test this please

**Comment by skuusela** [comment]
test this please

**Comment by skuusela** [comment]
Removed the test_mode parameter from the testing server DAFT settings, test this please

**Review by Arthil — APPROVED** [review]
This commit makes the code much clearer and removes variables which are not needed. Good job!

**Pull request merged**
