### PR TITLE
Add explicit error handling for flashing errors

### PR DESCRIPTION
**Pull request by Arthil**
Add explicit error handling for flashing errors to avoid unnecessary device blacklisting if testing fails. Now devices are blacklisted only if flashing fails.

Signed-off-by: Christian da Costa <christian.da.costa@intel.com>

### CODE REVIEW

**Comment by skuusela** [comment]
add to whitelist

**Comment by skuusela** [comment]
ok to test

**Comment by okartau** [comment]
add to whitelist

**Comment by skuusela** [comment]
Looks good but if you want to make cosmetic changes I would like to have them on separate commit. I don't mind few of those in the same one but if most of the lines you change are cosmetic, it's a bit too much.

**Pull request closed without merging**
