### PR TITLE
README.MD: Support Image SSH Instructions Update

### PR DESCRIPTION
**Pull request by playwithreality**
A new method to add SSH keys to support image.

Signed-off-by: Sami Nieminen <sami1.nieminen@intel.com>

### CODE REVIEW

**Comment by Arthil** [comment]
Test this please.

**Comment by playwithreality** [comment]
I should try this one more time on the laptop just in case. Was also thinking that this PR might be obsolete after all.

**Comment by Arthil** [comment]
@samniem What is the status of this PR?

**Comment by playwithreality** [comment]
@Arthil It is obsolete so I will close it

**Pull request closed without merging**
